name = "MyNewPackage"
uuid = "18458504-7572-479e-bfef-d235309142bf"
authors = ["Florian Oswald <florian.oswald@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
